language: python
python:
  - 3.6
install:
  - pip install awscli boto3 requests requests_toolbelt
branches:
  only:
    - master
script:
  - python build_scripts/build.py
before_deploy:
  - VERSION=$(cat build_scripts/version.txt)
  - CHANGELOG=$(cat build_scripts/changelog.md)
  - IFS='/'; BASENAME=($TRAVIS_REPO_SLUG); unset IFS;
  - RELEASE_NAME="${BASENAME[1]} $VERSION"
  - echo $VERSION
  - git config --local user.name "ChrisAdderley"
  - git config --local user.email "cadderley@gmail.com"
  - git remote set-url origin https://ChrisAdderley:${GITHUB_OAUTH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
  # Only tag if this is the first before_deploy (runs for all providers)
  - >
    if ! [ "$BEFORE_DEPLOY_RUN" ]; then
      export BEFORE_DEPLOY_RUN=1;
      git tag $VERSION;
      git push origin $VERSION;
    fi
deploy:
  - provider: script
    script: python build_scripts/deploy.py --curse
    skip_cleanup: true
    on:
      condition: $TRAVIS_BRANCH = master
  - provider: script
    script: python build_scripts/deploy.py --spacedock
    skip_cleanup: true
    on:
      condition: $TRAVIS_BRANCH = master
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: "nertea-ksp-modding-releases"
    local_dir: deploy
    skip_cleanup: true
    acl: public_read
    region: us-east-2
    upload-dir: station-parts-expansion-redux
    on:
      condition: $TRAVIS_BRANCH = master
  - deploy:
    provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    file_glob: true
    file: deploy/*
    body: "$CHANGELOG"
    name: $RELEASE_NAME
    skip_cleanup: true
    on:
      tags: false
      condition: $TRAVIS_BRANCH = master
